agent:
  config:
    receivers:
      otlp:
        protocols:
          grpc:
    exporters:
      splunk_hec:
        endpoint: https://ingest.signalfx.com/v1/log
        token: splunkObservability.accessToken
      logging/info:
        loglevel: info
    service:
      pipelines:
        logs/profiling:
          exporters:
            - logging/info
            - splunk_hec
          processors:
            - memory_limiter
            - batch
          receivers:
            - otlp
splunkObservability:
  accessToken: $SPLUNK_ACCESS_TOKEN
  realm: $SPLUNK_REALM