agent:
  config:
    receivers:
      receiver_creator:
        receivers:
          smartagent/kafka:
            rule: type == "pod" && name matches "kafka"
            config:
              port: 5555
              type: collectd/kafka
              clusterName: aev-kafka
clusterReceiver:
  eventsEnabled: true
  config:
    receivers:
      kafkametrics:
        brokers: kafka:9092
        protocol_version: 2.0.0
        scrapers:
          - brokers
          - topics
          - consumers
    service:
      pipelines:
        metrics:
          receivers:
          - k8s_cluster
          - kafkametrics
